version: '3'

services:
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    networks:
      - nginx
    depends_on:
      - docs
      - collector
      - grafana

  panel-api:
    build: ./services/panel-api
    volumes:
      - ./services/panel-api:/app
    networks:
      - nginx

  docs:
    build: ./services/docs
    volumes:
      - ./docs:/mkdocs/docs
    networks:
      - nginx

  collector:
    build: ./services/collector
    depends_on:
      - influxdb
    networks:
     - nginx
     - influx

  influxdb:
    build: ./services/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - influx

  grafana:
    image: grafana/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - influxdb
    networks:
      - nginx
      - influx

volumes: 
  influxdb-data:

networks:
  nginx:
  influx:
