version: '3'

services:
  docs:
    build: ./services/docs
    ports:
      - 80:80
    volumes:
      - ./docs:/mkdocs/docs

  collector:
    build: ./services/collector
    ports:
      - 8000:80
    depends_on:
      - influxdb

  influxdb:
    build: ./services/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_PASSWORD}

  panel:
    build: ./services/panel
    ports:
      - 8001:80
    volumes:
      - ./services/panel:/app

  grafana:
    image: grafana/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - 3000:3000
    depends_on:
      - influxdb

volumes: 
  influxdb-data:
