version: '3'

services:
  collector:
    build: ./services/collector
    ports:
      - 8000:80
    # environment:
        # PORT: 80
    depends_on:
      - influxdb

  influxdb:
    build: ./services/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_PASSWORD}

  grafana:
    image: grafana/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - 3000:3000

      # Redis Service   
#   redis:
#     image: "redis:alpine" # Use a public Redis image to build the redis service    
#     restart: unless-stopped
#     networks:
#       - backend                
# Networks to be created to facilitate communication between containers
# networks:
#   backend:  

volumes: 
  influxdb-data:
